config/routes.rb
Rails.application.routes.draw do

  root 'bookshop#index'

  get '/basket' => 'basket#index'
  get '/basket/clear' => 'basket#clearbasket'
  get '/basket/:id' => 'basket#add'

  devise_for :users
  resources :users, only: [:index, :show]

  resources :books do
    resources :reviews, except: [:show, :index]
  end

  resources :carts do
    resources :lineitems
  end

  resources :lineitems
  resources :orders

  get 'page/about'

  get 'page/faqs'

end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :book
	belongs_to :order

end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  before_action :current_cart
  before_action :set_lineitem, only: [:show, :edit, :update, :destroy]

  # GET /lineitems
  # GET /lineitems.json
  def index
    @lineitems = Lineitem.all
  end

  def show
  end

  def new
    @lineitem = Lineitem.new
  end

  def edit
  end

  def create
    book = Book.find(params[:book_id])
    @lineitem = @cart.add_book(book.id)

    respond_to do |format|
      if @lineitem.save
        format.html { redirect_to root_path, notice: 'Lineitem was successfully created.' }
        format.json { render :show, status: :created, location: @lineitem }
      else
        format.html { render :new }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineitems/1
  # PATCH/PUT /lineitems/1.json
  def update
    respond_to do |format|
      if @lineitem.update(lineitem_params)
        format.html { redirect_to @lineitem, notice: 'Lineitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @lineitem }
      else
        format.html { render :edit }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1
  # DELETE /lineitems/1.json
  def destroy
    @lineitem.destroy
    respond_to do |format|
      format.html { redirect_to lineitems_url, notice: 'Lineitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineitem
      @lineitem = Lineitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lineitem_params
      params.require(:lineitem).permit(:book_id, :order_id, :quantity, :cart_id)
    end

end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/views/lineitems/_form.html.erb
<%= form_for(@lineitem) do |f| %>
  <% if @lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
      <% @lineitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.number_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lineitems/edit.html.erb
<h1>Editing Lineitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @lineitem %> |
<%= link_to 'Back', lineitems_path %>

app/views/lineitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lineitems</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Order</th>
      <th>Quantity</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineitems.each do |lineitem| %>
      <tr>
        <td><%= lineitem.book_id %></td>
        <td><%= lineitem.order_id %></td>
        <td><%= lineitem.quantity %></td>
        <td><%= lineitem.cart_id %></td>
        <td><%= link_to 'Show', lineitem %></td>
        <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
        <td><%= link_to 'Destroy', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lineitem', new_lineitem_path %>

app/views/lineitems/new.html.erb
<h1>New Lineitem</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @lineitem.book_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @lineitem.order_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @lineitem.quantity %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @lineitem.cart_id %>
</p>

<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>