config/routes.rb
Rails.application.routes.draw do

  root 'bookshop#index'

  get '/basket' => 'basket#index'
  get '/basket/clear' => 'basket#clearbasket'
  get '/basket/:id' => 'basket#add'

  devise_for :users
  resources :users, only: [:index, :show]

  resources :books do
    resources :reviews, except: [:show, :index]
  end

  resources :carts do
    resources :lineitems
  end

  resources :lineitems
  resources :orders

  get 'page/about'

  get 'page/faqs'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :lineitems
	has_many :reviews

# require 'observer'
	has_attached_file :image, styles: { :medium => "300x300>", :thumb => "100x100#"},
	default_url: "/images/:style/download.jpeg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	def self.search(search)
		if search
			where(["title LIKE ?","%#{search}%"])
		else
			all
		end
	end

# include Observable

#  attr_reader :price, :quantity

#  def initialize(price = 0, quantity = 3)
#    @price, @quantity = price, quantity
#    add_observer(Notifier.new)
#  end

  #def log(more)
#   	@price += more
#   	changed
#    	notify_observers(self, more)
#  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #before_action :must_be_admin
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  
  def titleindex
    @books = Book.search params[:query]
    unless @books.empty? #if !@modelnames.empty?
      render 'index'
    else
      flash[:notice] = 'No record matches that records'
      render 'index'
    end
  end

  def index 
    @books = Book.search(params[:search])
  end 

  def show
    @reviews = Review.where(book_id: @book.id).order("created_at DESC")
  end

  def new
    @book = Book.new
  end

  def search
    @books = Book.search params[:query]
    unless @books.empty? #if !@modelnames.empty?
      render 'index'
    else
      flash[:notice] = 'No record matches that records'
      render 'index'
    end
  end

  def edit
  end

  def create
    @book = Book.new(book_params) 

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @lineitem }
      else
        format.html { render :new }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    #def must_be_admin
    #  unless current_user && current_user.is_admin?
    #    redirect_to root_path, notice: "Only admin have access"
    #  end
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author, :title, :category, :kind, :price, :quantity, :image)
    end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><%= f.label :image %><br />
    <%= f.file_field :image %></div>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing Books</h1>

<%= form_tag books_path, :method => "get" do %> 
  <%= text_field_tag(:search, params[:search]) %> 
  <%= submit_tag "Search" %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Category</th>
      <th>Kind</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.author %></td>
        <td><%= book.title %></td>
        <td><%= book.category %></td>
        <td><%= book.kind %></td>
        <td><%= book.price %></td>
        <td><%= book.quantity %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><a href="/basket/<%= book.id %>"> Add to Basket</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="row shop">
  <div class="col-sm-4 col-md-3">
    <h4>Price : <span class="label label-info"> 
      <%= @book.price %></span></h4>
    <%= image_tag(@book.image.url(:medium), class: 'image') %>
    <h4>Price : <span class="label label-info"> <%= @book.quantity %></span></h4>
    <ul>
      <%= content_tag(:li, ("Author: " + @book.author)) %>
      <%= link_to content_tag(:li, ("Title: " + @book.title)) %>
      <%= content_tag(:li, ("Category: " + @book.category)) %>
      <%= content_tag(:li, ("Kind: " + @book.kind)) %>
    </ul>
  </div>

  <div class="feed">
    <h3>Social Feed Coming</h3>
    <% if @reviews.blank? %>
      <h3>No Comment just yet, Would you like to add the first Review</h3>
      <%= link_to "Write a Review", new_book_review_path(@book), class: "btn btn-danger" %>
      <% else %>
      <%= link_to "Write a Review", new_book_review_path(@book), class: "btn btn-danger" %>
        <% @reviews.each do |review| %>
          <div class="row">
            <p>
              <i><small>Commenter: <%= review.user.email %></small></i>
            </p>
             
            <div class="col-sm-9 well">
              <h5><%= review.rating %></h5>
              <p><h5><%= simple_format(review.comment) %></h5></p>
              <p><i>
                <span class='quiet'><small> <%= time_ago_in_words(review.created_at)%> ago</small></span>
              </i></p>
            </div>
            <hr/>
          </div>
        <% end %>
    <% end %>
  </div>
</div>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>