config/routes.rb
Rails.application.routes.draw do

  root 'bookshop#index'

  get '/basket' => 'basket#index'
  get '/basket/clear' => 'basket#clearbasket'
  get '/basket/:id' => 'basket#add'

  devise_for :users
  resources :users, only: [:index, :show]

  resources :books do
    resources :reviews, except: [:show, :index]
  end

  resources :carts do
    resources :lineitems
  end

  resources :lineitems
  resources :orders

  get 'page/about'

  get 'page/faqs'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :lineitems
	has_many :reviews

# require 'observer'
	has_attached_file :image, styles: { :medium => "300x300>", :thumb => "100x100#"},
	default_url: "/images/:style/download.jpeg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	def self.search(search)
		if search
			where(["title LIKE ?","%#{search}%"])
		else
			all
		end
	end

# include Observable

#  attr_reader :price, :quantity

#  def initialize(price = 0, quantity = 3)
#    @price, @quantity = price, quantity
#    add_observer(Notifier.new)
#  end

  #def log(more)
#   	@price += more
#   	changed
#    	notify_observers(self, more)
#  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :lineitems, :dependent => :destroy
	belongs_to :user
	
def add_book(book_id)
	current_item = lineitems.find_by_book_id(book_id) 
	if current_item
  		current_item.quantity += 1 
	else
  	current_item = lineitems.new(book_id: book_id)
  	current_item.quantity = 1 
	end
  	current_item 
	end
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :book
	belongs_to :order

end

app/models/notifier.rb
class Notifier
  def update(book, more)
    puts "The use has bought #{more} books, totaling #{book.price} new Price."
    puts "The book needs to be taken in for a price cut!" 
    if car.price & amp;lt;= car.quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :lineitems, dependent: :destroy

	def add_lineitems_from_cart(cart) 
		cart.lineitems.each do |item|
			item.cart_id = nil
			lineitems << item 
		end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :book
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#"},
  default_url: "/images/:style/download.jpeg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
 
  has_many :orders
  has_many :reviews, dependent: :destroy

  def full_name
    name.blank? ? email : name
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #before_action :must_be_admin
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  
  def titleindex
    @books = Book.search params[:query]
    unless @books.empty? #if !@modelnames.empty?
      render 'index'
    else
      flash[:notice] = 'No record matches that records'
      render 'index'
    end
  end

  def index 
    @books = Book.search(params[:search])
  end 

  def show
    @reviews = Review.where(book_id: @book.id).order("created_at DESC")
  end

  def new
    @book = Book.new
  end

  def search
    @books = Book.search params[:query]
    unless @books.empty? #if !@modelnames.empty?
      render 'index'
    else
      flash[:notice] = 'No record matches that records'
      render 'index'
    end
  end

  def edit
  end

  def create
    @book = Book.new(book_params) 

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @lineitem }
      else
        format.html { render :new }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    #def must_be_admin
    #  unless current_user && current_user.is_admin?
    #    redirect_to root_path, notice: "Only admin have access"
    #  end
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author, :title, :category, :kind, :price, :quantity, :image)
    end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
      if @cart.id == session[:cart_id]
      respond_to do |format|
        format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
        format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
	@books = Book.order("title asc").all
  end

  def about
  end

  def faqs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookshop_helper.rb
module BookshopHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_cart.html.erb
<html>
<body>
  <div id="columns">
  	<div id="side"> 
    	<div id="cart">
      	<% if @cart %>
        	<%= render @cart %>
      	<% end %>
    	</div>
  	</div>
	<div id="main">
 
	</div>
	</div>

</body> 
</html>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <nav id="nav">
  <div id="page_nav">
      <%= link_to " Home ", root_path %>
      <%= link_to " About ", page_about_path %>
      <%= link_to " FAQs ", page_faqs_path %>
      <%= link_to " Books ", books_path %>
            </button>
            <%= link_to "Book App", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <%= link_to 'Customer', 'users_path' %>
                <% if user_signed_in? %>
                  <%= link_to 'Profile',edit_user_registration_path %>
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                  <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
                <% else %>
                    <li><%= link_to 'Sign In', new_user_session_path %></li>
                    </li><%= link_to " Sign Up ", new_user_registration_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Demo</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
  <body>

  <%= render 'layouts/flash_messages' %>
  <%= render 'layouts/menu' %>
  <%= render 'layouts/cart' %>

  <div class="container">
    <%= yield %>


  </body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/faqs.html.erb
<h1>Page#faqs</h1>
<p>Find me in app/views/page/faqs.html.erb</p>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>